import { Inter } from "next/font/google";
import Head from "next/head";
import Hero from "./components/Hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Website Build</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Captur Photography" message="I capture moments in nature and keep them alive." />
    </div>
  );
}
